install:
 - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
 - texlua l3build.lua ctan -H --show-log-on-error

notifications:
  email:
    recipients:
      - latex3-commits@tug.org
    on_success: change
    on_failure: always
    on_start:   never

